SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR cortex-m4)

SET(THREADX_ARCH "cortex_m4")
SET(THREADX_TOOLCHAIN "gnu")

ADD_DEFINITIONS(-DARM_MATH_CM4 -DARM_MATH_MATRIX_CHECK -DARM_MATH_ROUNDING -D__FPU_PRESENT=1)

SET(MCPU_FLAGS "-mthumb -mcpu=cortex-m4")
SET(VFP_FLAGS "-mfloat-abi=soft")

set(MESSAGE_SEPARATOR "------------------------------------------------------")
MESSAGE(STATUS ${MESSAGE_SEPARATOR} ${MESSAGE_SEPARATOR})
MESSAGE(STATUS "**** Platform: ${MCPU_FLAGS} ${VFP_FLAGS} ****")
MESSAGE(STATUS ${MESSAGE_SEPARATOR} ${MESSAGE_SEPARATOR} "\n")

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/cross_compiler.cmake)
